buildscript = []
# TODO aarch64 and mac
[[platform_fixup.'cfg(target_os = "linux")'.buildscript]]
[platform_fixup.'cfg(target_os = "linux")'.buildscript.cxx_library]
name = "libz-sys-linux"
srcs = [
    "src/zlib/adler32.c",
    "src/zlib/compress.c",
    "src/zlib/crc32.c",
    "src/zlib/deflate.c",
    "src/zlib/infback.c",
    "src/zlib/inffast.c",
    "src/zlib/inflate.c",
    "src/zlib/inftrees.c",
    "src/zlib/trees.c",
    "src/zlib/uncompr.c",
    "src/zlib/zutil.c",
    "src/zlib/gzclose.c",
    "src/zlib/gzlib.c",
    "src/zlib/gzread.c",
    "src/zlib/gzwrite.c",
]
headers = ["src/zlib/*.h"]
compiler_flags = [
    "-O0",
    "-DSTDC",
    "-DZLIB_CONST",
    "-D_LARGEFILE64_SOURCE",
    "-D_POSIX_SOURCE",    

]
include_paths = ["src/zlib"]
[env]
OUT_DIR = "."

